import Head from 'next/head'
import Link from 'next/link'

const AuthPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Authentication</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/LogoKitchen.svg' />
      </Head>
      <div className='w-full max-w-xs mx-auto translate-y-1/2'>
        <form className='bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4'>
          <div className='mb-4'>
            <label className='block text-gray-700 text-sm font-bold mb-2' htmlFor='username'>
              Username
            </label>
            <input
              className='shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
              id='username'
              type='text'
              placeholder='Username'
            />
          </div>
          <div className='mb-6'>
            <label className='block text-gray-700 text-sm font-bold mb-2' htmlFor='password'>
              Password
            </label>
            <input
              className='shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline'
              id='password'
              type='password'
              placeholder='******************'
            />
            <p className='text-red-500 text-xs italic'>Please choose a password.</p>
          </div>
          <div className='mb-2'>
            <Link
              href={'/register'}
              className='align-baseline font-bold text-sm text-gray-500 hover:text-gray-800'
            >
              {`Don't have account?`}
            </Link>
          </div>
          <div className='flex items-center justify-between'>
            <button
              className='bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline'
              type='button'
            >
              Sign In
            </button>
            <Link
              className='inline-block align-baseline font-bold text-sm text-gray-500 hover:text-gray-800'
              href='#'
            >
              Forgot Password?
            </Link>
          </div>
        </form>
      </div>
    </>
  )
}

export default AuthPage
