import Head from 'next/head'

const GallleryPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Gallery</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/LogoKitchen.svg' />
      </Head>
      <div>Gallery</div>
    </>
  )
}

export default GallleryPage
